import React, { useState } from 'react';
import type { CampusMoment } from '../../../shared/types';
import { MapPin, Heart, Plus, Compass } from 'lucide-react';

interface Props { moments: CampusMoment[]; onAddMoment: (title: string, tag: string, location: string) => void; onJoinEvent: (id: number) => void; onQuickAction?: (actionText: string) => void; }

export default function PresenceCard({ moments, onAddMoment, onJoinEvent, onQuickAction }: Props) {
  const [text, setText] = useState(''); const [tag, setTag] = useState('学术讨论'); const [loc, setLoc] = useState('星空大学图书馆'); const [show, setShow] = useState(false);
  const tags = ['学术讨论','日常树洞','组队敲码','活动约件','求助寻物'];

  const submit = (e: React.FormEvent) => { e.preventDefault(); if (text.trim()) { onAddMoment(text, tag, loc); setText(''); setShow(false); } };

  return (
    <div className="bg-white rounded-[24px] border border-neutral-100 p-8 shadow-[0_8px_30px_rgb(0,0,0,0.012)] transition-all hover:shadow-[0_12px_40px_rgb(0,0,0,0.018)]">
      <div className="flex items-center justify-between mb-6"><div><span className="text-xs font-mono text-neutral-400 uppercase tracking-widest">MODULE 03 / CONNECT</span><h2 className="text-xl font-semibold text-neutral-900 tracking-tight mt-1 flex items-center gap-2">我在校园 <span className="text-xs px-2 py-0.5 rounded-full bg-neutral-900 text-white font-normal">Active</span></h2></div><button onClick={()=>setShow(!show)} className="flex items-center gap-1.5 px-3 py-1.5 border border-neutral-100 bg-neutral-50 hover:bg-neutral-900 hover:text-white transition-all rounded-xl text-xs font-medium"><Plus className="w-3.5 h-3.5" /><span>同步在校瞬间</span></button></div>
      <div className="mb-6 p-4 bg-neutral-50 rounded-2xl border border-neutral-200/40 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-neutral-900 flex items-center justify-center"><MapPin className="w-4 h-4 text-white" /></div><div><span className="text-[10px] text-neutral-400 block font-mono">CURRENT STATION</span><span className="text-xs font-semibold text-neutral-800">图书馆 4F-A区-独学空间舱</span></div></div><div className="flex gap-1.5"><span className="inline-flex h-2 w-2 rounded-full bg-emerald-500 animate-pulse mt-1" /><span className="text-xs text-neutral-500">自修修仙中...</span></div></div>
      {show && <form onSubmit={submit} className="mb-6 p-5 border border-neutral-100 rounded-2xl bg-neutral-50/50 space-y-4"><div><label className="block text-[10px] uppercase font-mono text-neutral-400 mb-1.5">分享想法</label><textarea value={text} onChange={e=>setText(e.target.value)} className="w-full bg-white border border-neutral-100 rounded-xl p-3 text-xs outline-none resize-none h-16" required /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-[10px] uppercase font-mono text-neutral-400 mb-1.5">标签</label><select value={tag} onChange={e=>setTag(e.target.value)} className="w-full bg-white border border-neutral-100 rounded-xl p-2.5 text-xs">{tags.map(t=><option key={t}>{t}</option>)}</select></div><div><label className="block text-[10px] uppercase font-mono text-neutral-400 mb-1.5">位置</label><input value={loc} onChange={e=>setLoc(e.target.value)} className="w-full bg-white border border-neutral-100 rounded-xl p-2.5 text-xs" /></div></div><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShow(false)} className="px-3.5 py-2 hover:bg-neutral-100 text-neutral-600 rounded-xl text-xs">取消</button><button type="submit" className="px-4 py-2 bg-neutral-900 text-white rounded-xl text-xs font-semibold hover:bg-neutral-800">一键登载 ✨</button></div></form>}
      <div className="space-y-4"><div className="flex items-center justify-between text-[11px] font-semibold text-neutral-400 uppercase mb-2"><span>本院推荐体验 & 社团活动</span><span className="flex items-center gap-1 text-[10px] text-neutral-500"><Compass className="w-3 h-3" /> 校园动态</span></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{moments.map(m=><div key={m.id} className="border border-neutral-100/80 rounded-2xl p-5 hover:border-neutral-200 transition-all bg-white"><div className="flex items-start justify-between gap-2 mb-3"><span className="text-[10px] px-2.5 py-0.5 rounded-full bg-neutral-50 border border-neutral-100 text-neutral-600 font-medium">{m.tag}</span><span className="text-[10px] text-neutral-400 font-mono">{m.timeLabel}</span></div><h3 className="text-[13px] font-medium text-neutral-800 mb-4 line-clamp-2 min-h-[36px]">{m.title}</h3><div className="flex items-center justify-between border-t border-neutral-50 pt-3 text-xs"><div className="flex items-center gap-1.5 text-neutral-400"><MapPin className="w-3 h-3" /><span className="text-[10px] max-w-[100px] truncate">{m.location}</span></div>{m.maxAttendees ? <button onClick={()=>onJoinEvent(m.id)} className={`px-3 py-1 rounded-lg text-[10px] font-semibold ${m.joined?'bg-emerald-50 text-emerald-600 border border-emerald-100/60':'bg-neutral-900 text-white hover:bg-neutral-800'}`}>{m.joined?'已加盟 ✓':`预挂号 (${m.currentAttendees}/${m.maxAttendees})`}</button> : <div className="flex items-center gap-1 text-neutral-400"><Heart className="w-3.5 h-3.5" /><span>{m.likes}</span></div>}</div></div>)}</div></div>
      {onQuickAction && <div className="mt-5 pt-4 border-t border-neutral-100 flex items-center justify-between text-xs"><span className="text-neutral-400">申请教室场地？</span><button onClick={()=>onQuickAction('帮我推荐一个安静、带有大屏设备的空教室。')} className="font-medium text-neutral-900 hover:text-neutral-600 flex items-center gap-1 hover:underline">校内场地速配 🚀</button></div>}
    </div>
  );
}
